/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCatCatchRouteImport } from './routes/api/cat-catch'
import { Route as ApiMp4RouteImport } from './routes/api/mp4'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatCatchRoute = ApiCatCatchRouteImport.update({
  id: '/api/cat-catch',
  path: '/api/cat-catch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMp4Route = ApiMp4RouteImport.update({
  id: '/api/mp4',
  path: '/api/mp4',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cat-catch': typeof ApiCatCatchRoute
  '/api/mp4': typeof ApiMp4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cat-catch': typeof ApiCatCatchRoute
  '/api/mp4': typeof ApiMp4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cat-catch': typeof ApiCatCatchRoute
  '/api/mp4': typeof ApiMp4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cat-catch' | '/api/mp4'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cat-catch' | '/api/mp4'
  id: '__root__' | '/' | '/api/cat-catch' | '/api/mp4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCatCatchRoute: typeof ApiCatCatchRoute
  ApiMp4Route: typeof ApiMp4Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cat-catch': {
      id: '/api/cat-catch'
      path: '/api/cat-catch'
      fullPath: '/api/cat-catch'
      preLoaderRoute: typeof ApiCatCatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp4': {
      id: '/api/mp4'
      path: '/api/mp4'
      fullPath: '/api/mp4'
      preLoaderRoute: typeof ApiMp4RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCatCatchRoute: ApiCatCatchRoute,
  ApiMp4Route: ApiMp4Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
